sonar.projectKey=devTalk
sonar.projectName=devTalk
sonar.sourceEncoding=UTF-8

sonar.sources=devTalk-be/src,devTalk-fe/actions,devTalk-fe/app,devTalk-fe/components,devTalk-fe/constants,devTalk-fe/lib,devTalk-fe/schemas,devTalk-fe/store,devTalk-fe/types,devTalk-fe/utils,devTalk-fe/proxy.ts
sonar.tests=devTalk-be/src/test,devTalk-fe
sonar.test.inclusions=devTalk-be/src/test/**/*.ts,devTalk-fe/**/*.test.ts,devTalk-fe/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,devTalk-be/src/test/**,devTalk-fe/**/*.test.ts,devTalk-fe/**/*.test.tsx

sonar.javascript.lcov.reportPaths=devTalk-be/coverage/lcov.info,devTalk-fe/coverage/lcov.info
sonar.typescript.lcov.reportPaths=devTalk-be/coverage/lcov.info,devTalk-fe/coverage/lcov.info